config/routes.rb
TicketWin::Application.routes.draw do

  root "pages#home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/terms", to: "pages#terms", as: "terms"
    get "/organizer_terms", to: "pages#organizer_terms", as: "organizer_terms"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  get "/checkin", to: "checkins#index", as: "checkin"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end


  resources :organizations, only: :show
  resources :events do
    resources :tickets, only: [:index, :update]
  end

  resources :orders, except: [:new, :show] do
    member { get 'checkout' }
  end
  get '/redeem/:redemption_code', to: 'orders#redeem', as: 'redeem_order'

  namespace :stripe do
    get 'connect'
    get 'confirm'
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  title              :string           not null
#  description        :text
#  start_date         :datetime
#  end_date           :datetime
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  status             :string
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  location           :string
#  organization_id    :integer
#

class Event < ActiveRecord::Base
  include ClassyEnum::ActiveRecord

  belongs_to :user
  belongs_to :organization
  has_many :tiers, dependent: :destroy
  has_many :tickets, through: :tiers
  accepts_nested_attributes_for :tiers, reject_if: lambda { |t| t[:name].blank? }

  sanitizes :description

  before_create :set_defaults

  scope :approved, -> { Event.where(status: 'live') }

  has_attached_file :image, :styles => { :medium => "600x900>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  classy_enum_attr :status, class_name: 'EventStatus', default: 'pending_approval'
  [ :pending_approval?, :live?, :expired? ].each { |status_predicate| delegate status_predicate, to: :status }

  def free?
    tiers.all? { |tier| tier.price == 0 }
  end

  def to_param
    [id, title.parameterize].join(?-)
  end

  private

  def set_defaults
    self.start_date ||= Time.now
    self.end_date ||= self.start_date + 4.hours
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # load_and_authorize_resource

  def index
    @events = Event.approved
  end

  def show
    @event = Event.find(params[:id])
    @tiers = @event.tiers.sort_by(&:level)
    @order = Order.new
  end

  def new
    @event = Event.new(user: current_user)
    5.times { @event.tiers.build }
    gon.push(stripe_authorized: @event.user.stripe_authorized?, stripe_message: session.delete(:stripe))
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      @event.tiers.each(&:provision_tickets)
      redirect_to @event, notice: 'Your event was created and all tickets provisioned.'
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    gon.push(stripe_authorized: @event.user.stripe_authorized?, stripe_message: session.delete(:stripe), editAction: true)
  end

  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:start_date, :end_date, :title, :description, :image,
      :location, tiers_attributes: [:level, :name, :description, :price, :unprovisioned_tickets])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for(@event, html: {class: 'form-horizontal'}) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
      - @event.errors.full_messages.each do |message|
        %li= message

  %h3 Payments &amp; Fees
  %br
  .col-sm-8
    .btn-group
      %button.btn.pricing-free{type:'button', onclick:"formatPricingFeatures(false);"} Free
      %button.btn.pricing-paid{type:'button', onclick:"formatPricingFeatures(true);"} Paid
    &nbsp; Choose to make your event free to customers or to charge for tickets.
    %p
    .jumbotron#payments-jumbo.text-center
      = image_tag 'stripe_logo.png', style: 'margin: auto; height: 75px;'
      %i.fa.fa-2x.fa-cc-visa
      %i.fa.fa-2x.fa-cc-mastercard
      %i.fa.fa-2x.fa-cc-amex
      %i.fa.fa-2x.fa-cc-discover
      %p
      .small.pricing-free
        %strong Free events can skip this section!
      .small
        You can connect an existing Stripe account or easily create a new one. Click below to connect and activate event pricing.
      %p
      %br
      %a.btn.btn-info.connect-stripe{href: stripe_connect_path}
        %strong Connect with Stripe
      - if @event.user.stripe_authorized?
        .text-success
          %br
          .well.small
            Authorization successful for
            = @event.user.email + "!"

            &nbsp;
            %span.label.label-success
              %i.fa.fa-lg.fa-check
              Authorized
              = @event.user.stripe_authorized_at.to_formatted_s(:short)
      %p.clearfix
      #stripe-comm.small


  .clearfix
  %h3 General Information
  %br
  .form-group
    = f.label :start_date, class: 'control-label col-sm-2'
    .col-sm-6
      = f.datetime_select :start_date
  .form-group
    = f.label :end_date, class: 'control-label col-sm-2'
    .col-sm-6
      = f.datetime_select :end_date
  .form-group
    = f.label :title, class: 'control-label col-sm-2'
    .col-sm-6
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :location, class: 'control-label col-sm-2'
    .col-sm-6
      = f.text_field :location, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label col-sm-2'
    .col-sm-6
      = f.text_area :description, class: 'form-control tinymce'
  .form-group
    = f.label :image, class: 'control-label col-sm-2'
    .col-sm-6
      = f.file_field :image, class: 'form-control'

  = tinymce

  %br
  #ticketing-section
    .tack.clearfix
      %h3 Tickets &amp; Pricing
      .action-bar.pull-right
        %a#remove-tier-btn{onclick: 'removeTierRow()', role: 'button', class: 'btn btn-danger', disabled: true}
          %i.fa.fa-trash
        %a#add-tier-btn{onclick: 'addTierRow()', role: 'button', class: 'btn btn-info'}
          %i.fa.fa-plus

    %table.table.table-striped#ticket-matrix
      %thead
        %tr
          %th Tier
          %th Tier name
          %th Description
          %th # of tickets
          %th $ / ticket
          %th Total $ / tier
      %tfoot
        %tr
          %td.tiers{colspan: 2}
          %td
          %td.tickets
          %td
          %td
            %pre.totals
      %tbody
        = f.fields_for :tiers do |ff|
          %tr
            %td
              %pre.tier= ff.index
              = ff.hidden_field :level, value: ff.index
            %td= ff.text_field :name, placeholder: "ex. VIP, General Admission", class: 'form-control'
            %td= ff.text_area :description, placeholder: "(optional)", class: 'form-control', rows: 2, cols: 25
            %td= ff.number_field :unprovisioned_tickets, value: 0, in: 0..5000, step: 1, size: 4, class: 'form-control form-control-inline affects-total tier-ticket'
            %td
              .input-group
                %span.input-group-addon.input-group-addon-inline $
                = number_field_tag :price_dollars, 0, in: 0..9999, size: 4, class: 'form-control form-control-inline affects-total tier-price'
                = ff.hidden_field :price, value: 0, class: 'price-cents'
                %span.input-group-addon.input-group-addon-inline .00
            %td
              %pre.tier-total $0.00

  %br
  .actions.row.text-right{style: 'margin-right: 5px;'}
    = f.submit class: 'btn btn-primary', data: { disable_with: 'Processing event... this may take a minute...' }

app/views/events/edit.html.erb
<h1>Event Manager</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="container-fluid">
  <h1>Events</h1>
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-sm-6 col-md-4"><%= render partial: 'shared/event_card', locals: { event: event } %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.haml
%h1 Create an event
%hr

= render 'form'

app/views/events/show.html.haml
.row
  .col-md-6
    %h1= @event.title
  .col-md-6
    %h3= weekday_with_time(@event.start_date)
.row
  .col-md-6= image_tag @event.image.url(:medium)
  .col-md-6
    %p= raw @event.description
    %p &nbsp;

    = form_for @order do |f|
      %table.table.table-striped#tickets-preorder
        %tbody
          - @tiers.each do |tier|
            - next unless tier.display?
            = hidden_field_tag 'event_id', @event.id
            %tr
              %td.media
                .media-body
                  %h5= "#{tier.name}"
                  .small= tier.description
              %td.small.text-right.price= tier.price_in_dollars
              %td
                = number_field_tag "tickets_tier_id_#{tier.id}", 0, in: 0..tier.available_for_purchase, size: 4, class: 'form-control tickets-to-purchase'
        %tfoot
          %td.preorder-ticket-sum.text-right
          %td.preorder-price-sum
          %td
            = f.submit 'Buy Now', data: { disable_with: 'Processing...' }, class: 'btn btn-primary', disabled: true, id: 'submit-preorder'
%br
.row
  .col-md-12.text-center
    %p
      = link_to 'Back', events_path
      &nbsp;
      - if user_signed_in?
        - if can? :edit, @event
          = link_to 'Manage this event', edit_event_path(@event), class: "btn btn-info"