config/routes.rb
TicketWin::Application.routes.draw do

  root "pages#home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/terms", to: "pages#terms", as: "terms"
    get "/organizer_terms", to: "pages#organizer_terms", as: "organizer_terms"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  get "/checkin", to: "checkins#index", as: "checkin"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end


  resources :organizations, only: :show
  resources :events do
    resources :tickets, only: [:index, :update]
  end

  resources :orders, except: [:new, :show] do
    member { get 'checkout' }
  end
  get '/redeem/:redemption_code', to: 'orders#redeem', as: 'redeem_order'

  namespace :stripe do
    get 'connect'
    get 'confirm'
  end
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Organization < ActiveRecord::Base
  has_many :events
  has_many :members, class_name: 'User'
  has_one :owner, class_name: 'User', foreign_key: 'owner_org_id'

  def to_param
    [id, name.parameterize].join(?-)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def show
    @organization = Organization.find(params[:id])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/show.html.erb
<div class="row text-center">
  <h1><%= @organization.name %></h1>
</div>

<!-- 
@organization.members
@organization.owner
@organization.events
 -->


<% @organization.events.each do |event| %>
  <div class="row text-center">
    <h4><%= event.title %></h4>
    <%= image_tag event.image(:thumb), class: "img-responsive img-center" %>
    <br />
    <%= link_to 'View', event_path(event), class: "btn btn-primary" %>
    <%= link_to 'Check in', event_tickets_path(event), class: "btn btn-default" %>
    <% if current_user.organization && can?(:read, current_user.organization) %>
      <%= link_to 'Dashboard', event_path(event), class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>