config/routes.rb
TicketWin::Application.routes.draw do

  root "pages#home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/terms", to: "pages#terms", as: "terms"
    get "/organizer_terms", to: "pages#organizer_terms", as: "organizer_terms"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  get "/checkin", to: "checkins#index", as: "checkin"

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end


  resources :organizations, only: :show
  resources :events do
    resources :tickets, only: [:index, :update]
  end

  resources :orders, except: [:new, :show] do
    member { get 'checkout' }
  end
  get '/redeem/:redemption_code', to: 'orders#redeem', as: 'redeem_order'

  namespace :stripe do
    get 'connect'
    get 'confirm'
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center list-inline">
        <%= render 'layouts/navigation_links' %>
        <br />
        <br />
        <p><small>
          &copy; <%= Time.now.year %> - Ticket Win! | Terms of Service: <%= link_to "For Users", terms_path %> - <%= link_to "For Event Organizers", organizer_terms_path %>
        </small></p>
      </div>

    </div>

  </div>
</div>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-61809080-1', 'auto');
ga('send', 'pageview');
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
       <%= link_to(image_tag("ticket_win_white.png", :width => 200, :class => "logo"), "/") %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
         <%= render 'layouts/navigation_links' %> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Contact", contact_path %></li>
<li><%= link_to "Events", events_path %></li>

<% if !user_signed_in? %>
  <li><%= link_to "Sign in", new_user_session_path %></li>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
  <li><%= link_to "Edit your account", edit_user_registration_path %></li>
  <% if current_user.admin? %>
    <li><%= link_to "Admin", admin_root_path %></li>
  <% end %>
  <li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
  <% if current_user.organization && can?(:read, current_user.organization) %>
    <li><%= link_to 'Manage Events', organization_path(current_user.organization), class: "btn btn-primary" %></li>
  <% end %>
<% end %>

<li><%= link_to 'New Event', new_event_path, class: "btn btn-default" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "TicketWin" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= Gon::Base.render_data camel_case: true, init: true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://use.edgefonts.net/source-sans-pro.js" %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <br />
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>